### ISSUE TITLE
Heatmap page needs to be parametrized

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#62]
Noted by @dongbohu in PR #59:

> (1) Since the heatmap is a separate page now (instead of modal), does it make sense to include the sample IDs in the URL instead of using a generic #/analysis-detail? That way if a user wants to show the heatmap to another user, he/she can just send the URL. (I understand that if there are too many samples involved in the heatmap, the URL may reach its maximum length, so we may need a better solution if this functionality is really needed.)

I fully agree that the heatmap state should be parametrized to make URL sharing work properly.

Steps to complete this work:
- [x] refactor the `analysis-detail` page to put the heatmap into a distinct component (https://github.com/greenelab/adage-server/issues/278)
- [x] update the heatmap's vega spec to show sample labels rather than IDs (https://github.com/greenelab/adage-server/issues/279)
- [x] separate the heatmap into its own "view" page, which can be parameterized to accept an MLModel and a list of sample IDs via the URL (https://github.com/greenelab/adage-server/issues/280)

**Comment by mhuyck** [comment]
Note: in addition to enabling URL sharing, this can also be used for integration between features within the site.

**Comment by mhuyck** [comment]
Making this work will probably require addressing a minor design flaw: the heatmap should be factored out rather than fully integrated with the sample bin as it is now. It is nice to have the UI integrated (IMO), but the two parts should be separate units that come together here.

**Comment by dongbohu** [comment]
True.

**Comment by mhuyck** [comment]
When turning the heatmap into a component, consider using https://github.com/cmap/morpheus.js -- noticed by @cgreene and capturing here from our Slack conversation.

**Comment by mhuyck** [comment]
The work on this can be further broken down into the following steps, each of which deserves its own issue:
- [ ] refactor the `analysis-detail` page to put the heatmap into a distinct component
- [ ] update the heatmap's vega spec to show sample labels rather than IDs
- [ ] separate the heatmap into its own "view" page, which can be parameterized to accept an MLModel and a list of sample IDs via the URL

**Comment by mhuyck** [comment]
See also https://github.com/greenelab/adage-server/issues/268 , where overall workflow changes are being worked out.
